'use client'

import './globals.css'
import './sassy.sass'

import { ThemeProvider } from 'next-themes'

import type { Metadata } from 'next'

import Navbar from '@/components/Navbar'
import Mode from '@/components/Mode'
import Footer from '@/components/Footer'
import Firefly from '@/components/Firefly'

import { Poppins, Kaushan_Script, Permanent_Marker } from 'next/font/google'
export const poppins = Poppins({ subsets: ['devanagari', 'latin', 'latin-ext'], weight: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ], display: 'swap', adjustFontFallback: false})
export const kaushan_script = Kaushan_Script({subsets:['latin'], weight: ['400'], display: 'swap', adjustFontFallback: false})
export const permanent_marker = Permanent_Marker({subsets:['latin'], weight: ['400'], display: 'swap', adjustFontFallback: false})

// export const metadata: Metadata = {
const metadata: Metadata = {
  title: 'Kenani',
  description: 'Generated by create next app',
}
// Dynamic metadata
// export async function generateMetadata({ params }) {
//   return {
//     title: {
//       default: 'Kenani'
//     }
//   }
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body>
          <ThemeProvider attribute='class'>

          <Navbar />

          <Mode />

          <Firefly />
              

            {children}

          
          <Footer />

          </ThemeProvider>

        </body>
      </html>
    </>
    
  )
}
